# Generated by Django 3.2.7 on 2023-01-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='count',
            new_name='failed_times',
        ),
    ]
