# Generated by Django 4.1.5 on 2023-01-26 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Warning',
        ),
        migrations.RenameField(
            model_name='warning',
            old_name='result',
            new_name='result_code',
        ),
    ]
