# Generated by Django 4.1.5 on 2023-01-26 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_request_warning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warning',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='api.url'),
        ),
    ]
